### PR TITLE
Various fixes and enhancements

### PR DESCRIPTION
**Pull request by Aramgutang**
We've made quite a few fixes in our fork that would be great to have incorporated into the main repository; here's a list:
- A few test-related bugs fixed, ensuring that the tests pass under various condifitions (including when the MEDIA_URL of the site is not '/media/').
- Unicode characters in JS files are now handled without failing.
- Added a "css_slate" management command that compiles all CSS files that use a compiler and sets their permissions to be globally writeable for the future, saving quite a bit of effort during deplyment. It also accepts "--chown" and "--chgrp" arguments, which will change the owner user and/or group to the one specified, providing a moer secure alternative to making the CSS files globally writeable.

### CODE REVIEW

**Comment by dziegler** [comment]
Thanks! I've been meaning to write something like your css_slate command for a while. I'm going to refactor the file concatenation part a little bit to make it a easier to grok for ordinary humans such as myself.

Whose name(s) should I add to the AUTHORS file?

**Comment by Aramgutang** [comment]
Sorry about the filename search part, my brain was in LISP mode when I was writing it. It's actually quite readable if you're familiar with functional languages.

You can add "Aram Dulyan" to the AUTHORS if you like.

**Comment by dziegler** [comment]
Haha, no problem, my lisp-fu is just not that strong.

**Comment by dziegler** [comment]
merged

**Pull request merged**
